# Generated by Django 4.0.6 on 2022-07-16 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_alter_ban_bandate_alter_case_createddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='case.case'),
        ),
        migrations.AlterField(
            model_name='ban',
            name='moderatorUserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderators', to='case.moderator'),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderators', to='case.case'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='case.case'),
        ),
    ]
