# Generated by Django 4.0.6 on 2022-07-16 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_alter_ban_case_alter_ban_moderatoruserid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ban',
            old_name='moderatorUserId',
            new_name='moderator',
        ),
    ]
