# Generated by Django 4.0.6 on 2022-07-16 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_rename_moderatoruserid_ban_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casebans', to='case.case'),
        ),
        migrations.AlterField(
            model_name='ban',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderatorbans', to='case.moderator'),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casemoderators', to='case.case'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casevotes', to='case.case'),
        ),
    ]
