# Generated by Django 4.0.6 on 2022-07-16 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_alter_ban_case_alter_ban_moderator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caseBans', to='case.case'),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caseModerators', to='case.case'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caseVotes', to='case.case'),
        ),
    ]
